MODEL_REPOS = {
    'bert': 'google-bert/bert-base-uncased',
    't5': 'google-t5/t5-large',
    'mistral': 'mistralai/Mistral-7B-Instruct-v0.3',
    'llama3': 'meta-llama/Llama-3.1-8B-Instruct',
    '4o_mini': 'gpt-4o-mini-2024-07-18',
    'o3_mini': 'o3-mini-2025-01-31',
    '4o': 'gpt-4o-2024-08-06',
}

MODEL_PATHS = {
    'llama3_degree_1': 'beanham/spatial_join_llama3_degree_1',
    'llama3_degree_2': 'beanham/spatial_join_llama3_degree_2',
    'llama3_degree_5': 'beanham/spatial_join_llama3_degree_5',
    'llama3_degree_10': 'beanham/spatial_join_llama3_degree_10',
    'llama3_degree_20': 'beanham/spatial_join_llama3_degree_20',
    'mistral_degree_1': 'beanham/spatial_join_mistral_degree_1',
    'mistral_degree_2': 'beanham/spatial_join_mistral_degree_2',
    'mistral_degree_5': 'beanham/spatial_join_mistral_degree_5',
    'mistral_degree_10': 'beanham/spatial_join_mistral_degree_10',
    'mistral_degree_20': 'beanham/spatial_join_mistral_degree_20', 
    '4o_mini_degree_1': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::ApLQ6JBH',
    '4o_mini_degree_2': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::At1OE2Tj',
    '4o_mini_degree_5': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::At1CaAjK',
    '4o_mini_degree_10': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::ApoepRH8',
    '4o_mini_degree_20': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AuRjRqQg',
    'bert_degree_1': 'beanham/spatial_join_bert_degree_1',
    'bert_degree_2': 'beanham/spatial_join_bert_degree_2',
    'bert_degree_5': 'beanham/spatial_join_bert_degree_5',
    'bert_degree_10': 'beanham/spatial_join_bert_degree_10',
    'bert_degree_20': 'beanham/spatial_join_bert_degree_20',
    'llama3_distance_1': 'beanham/spatial_join_llama3_distance_1',
    'llama3_distance_2': 'beanham/spatial_join_llama3_distance_2',
    'llama3_distance_3': 'beanham/spatial_join_llama3_distance_3',
    'llama3_distance_4': 'beanham/spatial_join_llama3_distance_4',
    'llama3_distance_5': 'beanham/spatial_join_llama3_distance_5',
    'mistral_distance_1': 'beanham/spatial_join_mistral_distance_1',
    'mistral_distance_2': 'beanham/spatial_join_mistral_distance_2',
    'mistral_distance_3': 'beanham/spatial_join_mistral_distance_3',
    'mistral_distance_4': 'beanham/spatial_join_mistral_distance_4',
    'mistral_distance_5': 'beanham/spatial_join_mistral_distance_5',
    '4o_mini_distance_1': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsFocGzQ',
    '4o_mini_distance_2': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsIZS7PJ',
    '4o_mini_distance_3': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsHyOjiz',
    '4o_mini_distance_4': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsdH1Xrx',
    '4o_mini_distance_5': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsdOZb2b',
    'bert_distance_1': 'beanham/spatial_join_bert_distance_1',
    'bert_distance_2': 'beanham/spatial_join_bert_distance_2',
    'bert_distance_3': 'beanham/spatial_join_bert_distance_3',
    'bert_distance_4': 'beanham/spatial_join_bert_distance_4',
    'bert_distance_5': 'beanham/spatial_join_bert_distance_5',
}

MODEL_PATHS_WEAK_LABELS = {
    'llama3_degree_1_weak': 'beanham/spatial_join_llama3_degree_1_weak',
    'llama3_distance_1_weak': 'beanham/spatial_join_llama3_distance_1_weak',
    '4o_mini_degree_1_weak': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B39ZnKI2',
}
MODEL_STEPS_PATHS = {
    'llama3_degree_step_1': 'outputs_llama3/degree/5/checkpoint-753',
    'llama3_degree_step_2': 'outputs_llama3/degree/5/checkpoint-1506',
    'llama3_degree_step_3': 'outputs_llama3/degree/5/checkpoint-2259',
    'llama3_degree_step_4': 'outputs_llama3/degree/5/checkpoint-3012',
    'llama3_degree_step_5': 'outputs_llama3/degree/5/checkpoint-3765',
    'mistral_degree_step_1': 'outputs_mistral/degree/10/checkpoint-754',
    'mistral_degree_step_2': 'outputs_mistral/degree/10/checkpoint-1508',
    'mistral_degree_step_3': 'outputs_mistral/degree/10/checkpoint-2262',
    'mistral_degree_step_4': 'outputs_mistral/degree/10/checkpoint-3016',
    'mistral_degree_step_5': 'outputs_mistral/degree/10/checkpoint-3770',
}