MODEL_REPOS = {
    'mistral': 'mistralai/Mistral-7B-Instruct-v0.3',
    'llama3': 'meta-llama/Llama-3.1-8B-Instruct',
    '4o_mini': 'gpt-4o-mini-2024-07-18',
    '4o': 'gpt-4o-2024-08-06',
    'gemini': 'gemini-2.0-flash',
    'claude': 'claude-3-5-haiku-20241022',
    'qwen_plus': 'qwen-plus',
    'qwen_max': 'qwen-max',
    'deepseek': 'deepseek-chat'
}

MODEL_PATHS = {
    'llama3_degree_1': 'beanham/spatial_union_llama3_degree_1',
    'llama3_degree_2': 'beanham/spatial_union_llama3_degree_2',
    'llama3_degree_3': 'beanham/spatial_union_llama3_degree_3',
    'llama3_degree_4': 'beanham/spatial_union_llama3_degree_4',
    'llama3_degree_5': 'beanham/spatial_union_llama3_degree_5',
    'mistral_degree_1': 'beanham/spatial_union_mistral_degree_1',
    'mistral_degree_2': 'beanham/spatial_union_mistral_degree_2',
    'mistral_degree_3': 'beanham/spatial_union_mistral_degree_3',
    'mistral_degree_4': 'beanham/spatial_union_mistral_degree_4',
    'mistral_degree_5': 'beanham/spatial_union_mistral_degree_5', 
    '4o_mini_degree_1': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0CFV6qQ',
    '4o_mini_degree_2': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0D25V3z',
    '4o_mini_degree_3': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0CvguXY',
    '4o_mini_degree_4': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0D2vh6l',
    '4o_mini_degree_5': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0CuidcL',
    'llama3_area_0.5': 'beanham/spatial_union_llama3_area_0.5',
    'llama3_area_0.6': 'beanham/spatial_union_llama3_area_0.6',
    'llama3_area_0.7': 'beanham/spatial_union_llama3_area_0.7',
    'llama3_area_0.8': 'beanham/spatial_union_llama3_area_0.8',
    'llama3_area_0.9': 'beanham/spatial_union_llama3_area_0.9',
    'mistral_area_0.5': 'beanham/spatial_union_mistral_area_0.5',
    'mistral_area_0.6': 'beanham/spatial_union_mistral_area_0.6',
    'mistral_area_0.7': 'beanham/spatial_union_mistral_area_0.7',
    'mistral_area_0.8': 'beanham/spatial_union_mistral_area_0.8',
    'mistral_area_0.9': 'beanham/spatial_union_mistral_area_0.9', 
    '4o_mini_area_0.5': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0ExSGxs',
    '4o_mini_area_0.6': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0Eo52ak',
    '4o_mini_area_0.7': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0Ews1Tx',
    '4o_mini_area_0.8': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0Ew8Tso',
    '4o_mini_area_0.9': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::B0FkYrfz',
}

MODEL_GENERALIZATION_PATHS = {    
    'llama3_degree_1': 'beanham/spatial_join_llama3_degree_1',
    'llama3_degree_2': 'beanham/spatial_join_llama3_degree_2',
    'llama3_degree_5': 'beanham/spatial_join_llama3_degree_5',
    'llama3_degree_10': 'beanham/spatial_join_llama3_degree_10',
    'llama3_degree_20': 'beanham/spatial_join_llama3_degree_20',
    'mistral_degree_1': 'beanham/spatial_join_mistral_degree_1',
    'mistral_degree_2': 'beanham/spatial_join_mistral_degree_2',
    'mistral_degree_5': 'beanham/spatial_join_mistral_degree_5',
    'mistral_degree_10': 'beanham/spatial_join_mistral_degree_10',
    'mistral_degree_20': 'beanham/spatial_join_mistral_degree_20', 
    '4o_mini_degree_1': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::ApLQ6JBH',
    '4o_mini_degree_2': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::At1OE2Tj',
    '4o_mini_degree_5': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::At1CaAjK',
    '4o_mini_degree_10': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::ApoepRH8',
    '4o_mini_degree_20': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AuRjRqQg',
    'llama3_distance_1': 'beanham/spatial_join_llama3_distance_1',
    'llama3_distance_2': 'beanham/spatial_join_llama3_distance_2',
    'llama3_distance_3': 'beanham/spatial_join_llama3_distance_3',
    'llama3_distance_4': 'beanham/spatial_join_llama3_distance_4',
    'llama3_distance_5': 'beanham/spatial_join_llama3_distance_5',
    'mistral_distance_1': 'beanham/spatial_join_mistral_distance_1',
    'mistral_distance_2': 'beanham/spatial_join_mistral_distance_2',
    'mistral_distance_3': 'beanham/spatial_join_mistral_distance_3',
    'mistral_distance_4': 'beanham/spatial_join_mistral_distance_4',
    'mistral_distance_5': 'beanham/spatial_join_mistral_distance_5',
    '4o_mini_distance_1': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsFocGzQ',
    '4o_mini_distance_2': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsIZS7PJ',
    '4o_mini_distance_3': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsHyOjiz',
    '4o_mini_distance_4': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsdH1Xrx',
    '4o_mini_distance_5': 'ft:gpt-4o-mini-2024-07-18:uw-howe-lab::AsdOZb2b',
}
